title: "The CodeLores"
description: "A tech comic series blending code, humor, and storytelling."
url: "https://aishakarigar.github.io"
baseurl: "/TheCodeLores"


theme: minima   # You can also try: cayman, jekyll-theme-cayman, etc.


# Markdown & formatting
markdown: kramdown
highlighter: rouge

# Include extra assets
include:
  - assets
  - comics

# Plugins (optional, but makes site richer)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
